In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [ ]:
np.array([[1,2],[1,2],[2,4]])

array([[1, 2],
       [1, 2],
       [2, 4]])

In [ ]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [ ]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.random((3,4))


array([[0.94048693, 0.31077667, 0.56533286, 0.64761775],
       [0.63557916, 0.06614668, 0.42812654, 0.60259529],
       [0.14548859, 0.54531583, 0.00597246, 0.47975105]])

In [ ]:
np.linspace(-9,9,12)

array([-9.        , -7.36363636, -5.72727273, -4.09090909, -2.45454545,
       -0.81818182,  0.81818182,  2.45454545,  4.09090909,  5.72727273,
        7.36363636,  9.        ])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a1=np.arange(100)
a2=np.arange(10).reshape(2,5)
a3=np.arange(16).reshape(2,2,2,2)

In [ ]:
a1.ndim

1

In [ ]:
a3.ndim

4

In [ ]:
a3.shape

(2, 2, 2, 2)

In [ ]:
a3.astype(np.int32)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]], dtype=int32)

In [ ]:
#scaler operations
a3**3

array([[[[   0,    1],
         [   8,   27]],

        [[  64,  125],
         [ 216,  343]]],


       [[[ 512,  729],
         [1000, 1331]],

        [[1728, 2197],
         [2744, 3375]]]])

In [ ]:
#relational operations
a3>2

array([[[[False, False],
         [False,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

In [ ]:
#vector operations for same dimentions
t1=np.arange(2,10)
t2=np.arange(1,9)
t1+t2
t1-t2
t2**t1
t1*t2

array([ 2,  6, 12, 20, 30, 42, 56, 72])

**ARRAY** **Functions**

In [ ]:
n1=np.arange(1,11).reshape(5,2)
n1=np.round(n1*100)
n1


array([[ 100,  200],
       [ 300,  400],
       [ 500,  600],
       [ 700,  800],
       [ 900, 1000]])

In [ ]:
np.max(n1)


1000

In [ ]:
np.prod(n1)

4013587096064229376

In [ ]:
np.max(n1,axis=1)

array([ 200,  400,  600,  800, 1000])

In [ ]:
np.mean(n1)

550.0

In [ ]:
np.median(n1)


550.0

In [ ]:
np.var(n1)

82500.0

In [ ]:
np.std(n1)

287.22813232690146

In [ ]:
#Trignometric functions
np.sin(a1[2])

0.9092974268256817

In [ ]:
d1=np.arange(1,16,2).reshape(2,4)
d1.ndim

2

In [ ]:
#Indexing of np_array
d1[1,0].ndim

0

In [ ]:
d2=np.arange(1,17).reshape(2,4,2)


In [ ]:
d2[1,2,1]

14

In [ ]:
#slicing
d3=np.arange(1,10)
d3[1:3]

array([2, 3])

In [ ]:
d1.reshape(2,4)


array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [ ]:
d1.shape[1]

4

In [ ]:
d1[:,1::d1.shape[1]-2]

array([[ 3,  7],
       [11, 15]])

In [ ]:
d1[:,[0,-1]]=0
d1

array([[ 0,  3,  5,  0],
       [ 0, 11, 13,  0]])

In [ ]:
np.nan*0

nan

In [ ]:
np.nan==np.nan

False

In [ ]:
np.inf

inf

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan-np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == np.round(3*0.1 , 1)

True

In [ ]:
np.round(3*0.1 , 1)

0.3

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
np.diag(np.arange(1,4),k=-2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
print(np.unravel_index(13,(6,7,8)))

(0, 1, 5)


In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
np.tile(np.array([[1,2]]),(2,1))

array([[1, 2],
       [1, 2]])

In [ ]:
color =np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

In [ ]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
Z=np.arange(11)

In [ ]:
Z[(3<Z) & (5<Z)]*=1
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(sum(range(5),-1))

9


In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
2<<Z>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday=np.datatime64('today')-np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [ ]:

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
np.arange('2023-07','2023-08',dtype='datetime64[D]')

array(['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04',
       '2023-07-05', '2023-07-06', '2023-07-07', '2023-07-08',
       '2023-07-09', '2023-07-10', '2023-07-11', '2023-07-12',
       '2023-07-13', '2023-07-14', '2023-07-15', '2023-07-16',
       '2023-07-17', '2023-07-18', '2023-07-19', '2023-07-20',
       '2023-07-21', '2023-07-22', '2023-07-23', '2023-07-24',
       '2023-07-25', '2023-07-26', '2023-07-27', '2023-07-28',
       '2023-07-29', '2023-07-30', '2023-07-31'], dtype='datetime64[D]')

In [ ]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
w1=np.ones(3)
w2=np.ones(3)
np.add(w1,w2,out=w1)
np.divide(w1,2,out=w1)
np.negative(w1,out=w1)
np.multiply(w1,w2,out=w1)


array([-1., -1., -1.])

In [ ]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
r=np.random.random(10)
r.sort()
r


array([0.11801673, 0.16929409, 0.17643404, 0.19451896, 0.25219561,
       0.46895713, 0.729878  , 0.79784823, 0.86890212, 0.87297006])

In [ ]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
np.add.reduce(Z)

45.0

In [ ]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
equal = np.array_equal(d1,d2)
equal

False

In [ ]:
### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
T

array([1.32633706, 1.01114405, 0.55298377, 0.34019765, 1.43415111,
       1.5322097 , 1.12505941, 1.26900868, 0.80347733, 0.19784504])

In [ ]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

Z = np.random.random(10)
Z[Z.argmax()]=0

In [ ]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
np.subtract.outer(X, Y)

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [ ]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Z = np.arange(100)
v = np.random.uniform(0,100)
Z[(np.abs(Z-v)).argmin()]

80

In [ ]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

In [ ]:
#### 59. How to sort an array by the nth column? (★★☆)

print(d1[d1[:,1].argsort()])

[[ 0  3  5  0]
 [ 0 11 13  0]]


In [ ]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)

print(np.isnan(Z).all(axis=0))

False


In [ ]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
np.bincount(I,X)

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


In [ ]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[39 49 59 37]
 [57 49 56 44]
 [53 57 53 41]]


In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Fast version
np.sum(A * B.T, axis=1)

In [ ]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

In [ ]:
#### 72. How to swap two rows of an array? (★★★)


A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
