In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [4]:
np.array([[1,2],[1,2],[2,4]])

array([[1, 2],
       [1, 2],
       [2, 4]])

In [5]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [6]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.random.random((3,4))


array([[0.4433628 , 0.22848032, 0.00484932, 0.77863869],
       [0.46921775, 0.7993932 , 0.05436717, 0.16542448],
       [0.11445609, 0.15334615, 0.65335818, 0.50472248]])

In [10]:
np.linspace(-9,9,12)

array([-9.        , -7.36363636, -5.72727273, -4.09090909, -2.45454545,
       -0.81818182,  0.81818182,  2.45454545,  4.09090909,  5.72727273,
        7.36363636,  9.        ])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a1=np.arange(100)
a2=np.arange(10).reshape(2,5)
a3=np.arange(16).reshape(2,2,2,2)

In [13]:
a1.ndim

1

In [14]:
a3.ndim

4

In [15]:
a3.shape

(2, 2, 2, 2)

In [16]:
a3.astype(np.int32)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]], dtype=int32)

In [17]:
#scaler operations
a3**3

array([[[[   0,    1],
         [   8,   27]],

        [[  64,  125],
         [ 216,  343]]],


       [[[ 512,  729],
         [1000, 1331]],

        [[1728, 2197],
         [2744, 3375]]]])

In [18]:
#relational operations
a3>2

array([[[[False, False],
         [False,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

In [19]:
#vector operations for same dimentions
t1=np.arange(2,10)
t2=np.arange(1,9)
t1+t2
t1-t2
t2**t1
t1*t2

array([ 2,  6, 12, 20, 30, 42, 56, 72])

**ARRAY** **Functions**

In [20]:
n1=np.arange(1,11).reshape(5,2)
n1=np.round(n1*100)
n1


array([[ 100,  200],
       [ 300,  400],
       [ 500,  600],
       [ 700,  800],
       [ 900, 1000]])

In [21]:
np.max(n1)


1000

In [22]:
np.prod(n1)

4013587096064229376

In [23]:
np.max(n1,axis=1)

array([ 200,  400,  600,  800, 1000])

In [24]:
np.mean(n1)

550.0

In [25]:
np.median(n1)


550.0

In [26]:
np.var(n1)

82500.0

In [27]:
np.std(n1)

287.22813232690146

In [28]:
#Trignometric functions
np.sin(a1[2])

0.9092974268256817

In [29]:
d1=np.arange(1,16,2).reshape(2,4)
d1.ndim

2

In [30]:
#Indexing of np_array
d1[1,0].ndim

0

In [31]:
d2=np.arange(1,17).reshape(2,4,2)


In [32]:
d2[1,2,1]

14

In [33]:
#slicing
d3=np.arange(1,10)
d3[1:3]

array([2, 3])

In [34]:
d1.reshape(2,4)


array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [35]:
d1.shape[1]

4

In [36]:
d1[:,1::d1.shape[1]-2]

array([[ 3,  7],
       [11, 15]])

In [37]:
d1[:,[0,-1]]=0
d1

array([[ 0,  3,  5,  0],
       [ 0, 11, 13,  0]])

In [38]:
np.nan*0

nan

In [39]:
np.nan==np.nan

False

In [40]:
np.inf

inf

In [41]:
np.inf > np.nan

False

In [42]:
np.nan-np.nan

nan

In [43]:
np.nan in set([np.nan])

True

In [44]:
0.3 == np.round(3*0.1 , 1)

True

In [45]:
np.round(3*0.1 , 1)

0.3

In [46]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [47]:
np.diag(np.arange(1,4),k=-2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

In [48]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [49]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [50]:
print(np.unravel_index(13,(6,7,8)))

(0, 1, 5)


In [51]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
np.tile(np.array([[1,2]]),(2,1))

array([[1, 2],
       [1, 2]])

In [53]:
color =np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

In [54]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [79]:
Z=np.arange(11)

In [74]:
Z[(3<Z) & (5<Z)]*=1
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
print(sum(range(5),-1))

9


In [77]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [80]:
2<<Z>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])